include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.6-slim
  script:
    - INGEST_API=https://api.ingest.dev.archive.data.humancellatlas.org
    - nosetests