include:
  remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'

Test:
  stage: test
  image: quay.io/ebi-ait/ingest-base-images:python_3.10-slim
  variables:
    INGEST_API : https://api.ingest.dev.archive.data.humancellatlas.org/
  before_script:
    - pip install --upgrade pip
    - pip install pip-tools
    - pip-sync requirements.txt requirements-dev.txt
  script:
    - nosetests --with-xunit
  artifacts:
    paths:
      - nosetests.xml
    reports:
      junit: nosetests.xml