include:
  - remote: 'https://raw.githubusercontent.com/ebi-ait/gitlab-ci-templates/master/build-release-deploy.yml'
  - template: Code-Quality.gitlab-ci.yml

Unit Test:
  image: quay.io/ebi-ait/ingest-base-images:python_3.6-slim
  variables:
    INGEST_API : https://api.ingest.dev.archive.data.humancellatlas.org/
  script:
    - apt-get update
    - apt-get install -y git
    - pip install -r requirements-dev.txt
    - nosetests --with-xunit
  artifacts:
    paths:
      - nosetests.xml
    reports:
      junit: nosetests.xml

code_quality:
  services:
  variables:
    DOCKER_TLS_CERTDIR: /certs
    CODE_QUALITY_IMAGE: "quay.io/gitlab-mirror/codequality"
