@startuml

title Geo import dcp-628

actor Wrangler
participant UI
box broker
  participant Broker
  participant GeoScript
  participant ProjectCreator 
end box

note over ProjectCreator : a new service in the Broker

Wrangler -> UI : import geo accession
UI -> Broker : import from geo
Broker -> GeoScript : import from Geo
GeoScript --> Broker : project metadata
Broker -> ProjectCreator : create project in ingest

ProjectCreator -> ProjectCreator :  create project 
ProjectCreator --> Broker :  return project_uuid
Broker --> UI : spreadsheet, project_uuid
UI --> Wrangler : download spreadsheet

@enduml
